### ISSUE TITLE
Broken link to ETS ontology

### ISSUE THREAD

**Issue by dlebauer** [EcologicalTraitData/ETS#27]
This link in the README does not load https://terminologies.gfbio.org/terminology/?ontology=ETS. Is there a new link or alternative way to reach this page?

**Comment by DavidFichtmueller** [comment]
Hey David, 
since yesterday we have an issue on the backend of the GFBio Terminology Service. We are aware of this issue, but fixing it turns out to be a bit tricky, hopefully it should be back online soon. So this is not a permanent issue. 
An alternative would be to go to our dev-server: https://dev-gfbio.bgbm.org/terminology/?ontology=ETS . The classical documentation pages however still work: https://terminologies.gfbio.org/terms/ets/pages/ . 
I will keep you updated on our progress, so I am leaving this issue open until then.
Cheers, David

**Comment by DavidFichtmueller** [comment]
Hey David, the issue has been fixed now. Thanks for pointing this out. All the best, David

**Comment by dlebauer** [comment]
Thank you!
